apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-apps
  labels:
    app: java-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-k8s-app
  template:
    metadata:
      labels:
        app: java-k8s-app
    spec:
      containers:
      - name: java-k8s-app
        image: techietech/java-k8s-app:latest
        ports: 
        - containerPort: 8080
        resources:
          requests: 
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
            